services:

  rate-limiter:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - local-network  

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - local-network

volumes:
  redis_data:
    driver: local

networks:
  local-network: